---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-nfd-gpu-permissions
  namespace: openshift-nfd
  annotations:
    argocd.argoproj.io/sync-wave: "299"
rules:
- apiGroups:
  - "nfd.openshift.io"
  - "nvidia.com"
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-nfd-gpu-permissions-binding
  annotations:
    argocd.argoproj.io/sync-wave: "299"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-nfd-gpu-permissions
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
