apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-policy.yaml
  - driver.yaml
  - nodefeaturediscovery.yaml

# Common labels and annotations for all resources
commonLabels:
  app.kubernetes.io/part-of: gpu-operator

# Set sync wave for Argo CD to ensure this is applied after operators are ready
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true