apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nodefeaturediscovery.yaml  # Sync wave 100
  - cluster-policy.yaml        # Sync wave 200
  - driver.yaml                # Sync wave 200
  - argocd-permissions.yaml    # Sync wave 299 (will be applied before 300)

# Common labels and annotations for all resources
commonLabels:
  app.kubernetes.io/part-of: gpu-operator

# Set sync wave for Argo CD to ensure this is applied after operators are ready
commonAnnotations:
  argocd.argoproj.io/sync-wave: "200"  # Default sync wave for resources without explicit wave
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true